baseURL = "https://farmtips.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website Eduardo Muller Gruhn"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs/"

# runtime = "shiny"
# output = "html_document"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
