---
author: Eduardo
date: "2021-08-15"
description: Uma breve apresentação de produto para Agricultura Digital
series:
- series-setup
title: Painel de eficiência agronômica
tags:
- wheat
- trigo
- ndvi
- fungicidas
- ferrugem
- pdi
runtime: shiny
output: html_document
---

Nessa sessão vc poderá ter acesso a uma dasboard agronomica

<!--more-->

Quando trabalhamos com sistemas de medição de eficiência agronômica nos deparamos com volumes muito grandes de dados. Informações de toda a natureza que no ambiente experimental dispendiam consideráveis investimentos de tempo e recursos.

Apessar disso, tão importante quanto a realização é o valor dos resultados. Normalmente diante de tanta informação torna-se cada vez mais importante uma visualização rápida para tomada de decisão ágil e confiável. Dessa maneira 
Abaixo segue o direcionamento de um painel de testes agronômicos pelo qual você poderá tirar conclusões úteis na escolha e compra de produtos.



<iframe src="https://eduardomullergruhn.shinyapps.io/Painel1/" height="800" width="100%" frameborder="no"></iframe>


Para uma melhor experiência abaixo segue o link do painel:

<b>https://eduardomullergruhn.shinyapps.io/Painel1/</b>

